version: "3.9"
services:
  backend:
    build: ./server
    ports:
      - "8080:8080"
    networks:
      - dtnetwork
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - dtnetwork
networks:
  dtnetwork:
